# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output/dro-rebuttal-nodiv
      name: dsprites_loc
  max_epochs: 150
  # max_steps: 10000
  val_check_interval: 50
  num_sanity_val_steps: 0
model:
  model_name: vit-b16-224-dino
  training_mode: lora
  optimizer: dro
  lr: 0.5
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
  rho: 0.05
  lora_r: 8
  lora_alpha: 8
  num_particles: 4
  bound: 0.03
  distance: euclid
  clip: 0.15
  name_dataset: dsprites_loc
  alpha_div: 0
data:
  train_aug: True
  dataset: dsprites_loc
  root: ../vtab-1k/dsprites_loc
  size: 224
  batch_size: 64
  workers: 4
model_checkpoint:
  dirpath: saved_checkpoints
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
