# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output/dro-fisher
      name: cifar100
  max_epochs: 50
  val_check_interval: 50
  num_sanity_val_steps: 0
model:
  sigma: 1.4
  model_name: vit-b16-224-dino
  training_mode: lora
  optimizer: dro
  lr: 0.12
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 500
  rho: 0.06
  lora_r: 2
  lora_alpha: 2
  num_particles: 4
  cov_mat: True
  max_num_models: 20
  use_sam: True
  start_swa_step: 200
  swa_freq: 1
  use_swa_svgd: False
  use_sym_kl: False
  bound: 0.03
  distance: fisher
data:
  train_aug: False
  dataset: cifar100
  root: ../vtab-1k/cifar100
  size: 224
  batch_size: 24
  workers: 4
model_checkpoint:
  dirpath: saved_checkpoints
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
